/**
 * Bundles the ChoiceScript engine into public/engine/ so the app is a fully
 * static site with no server of any kind.
 *
 * Order matters: scene.js and navigator.js must come before anything that
 * touches Scene.prototype. core/stats.js overrides *stat_chart, and when it
 * loaded first the override silently bailed on `typeof Scene === "undefined"`,
 * letting the stock implementation draw raw DOM into the page.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const ENGINE_FILES = [
  'engine/persist.js',
  'engine/util.js',
  'engine/core/bus.js',
  'engine/core/stubs.js',
  'engine/core/legacy.js',
  'engine/core/bridge.js',
  'engine/scene.js',
  'engine/navigator.js',
  'engine/core/shell.js',
  'engine/core/stats.js',
  'engine/core/achievements.js',
  'engine/core/saves.js',
  'engine/core/settings.js',
  'engine/core/api.js',
];

const preamble =
  '/* ChoiceScript engine bundle. Generated by scripts/build-engine.mjs. */\n' +
  'var isWeb = true;\nvar rootDir = "";\nwindow.storeName = null;\n' +
  /* scene.js passes a global `main` to printButton. In the stock layout that
   * exists only because the shell has <div id="main"> and browsers auto-create
   * window.<id>. A front end with its own root would hit "main is not defined". */
  'if (typeof window.main === "undefined" || !window.main) {\n' +
  '  window.main = document.getElementById("main") || document.body;\n}\n';

const bundle =
  preamble +
  ENGINE_FILES.map(
    (f) => `\n/* ===== ${f} ===== */\n${readFileSync(join(root, f), 'utf8')}\n;\n`,
  ).join('');

const theme = ['engine/theme/tokens.css', 'engine/theme/themes.css']
  .map((f) => `/* ===== ${f} ===== */\n${readFileSync(join(root, f), 'utf8')}`)
  .join('\n');

mkdirSync(join(root, 'public/engine'), { recursive: true });
writeFileSync(join(root, 'public/engine/bundle.js'), bundle);
writeFileSync(join(root, 'public/engine/theme.css'), theme);

console.log(
  `engine bundle: ${(bundle.length / 1024).toFixed(0)} kB · theme: ${(theme.length / 1024).toFixed(0)} kB`,
);
