//! Every path the app touches, derived from one place.
//!
//! Ids and store names arrive from the front end, which means they arrive from
//! whatever the front end was handed. Nothing here builds a path without
//! validating the component first, so a crafted id cannot walk out of the
//! library directory.

use std::path::PathBuf;
use tauri::{AppHandle, Manager};

/// Ids are generated by `crypto.randomUUID()` with the dashes stripped and
/// truncated to 16 characters, so this is deliberately narrower than the
/// filesystem allows.
pub fn validate_id(id: &str) -> Result<&str, String> {
    let ok = id.len() >= 8
        && id.len() <= 32
        && id.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit());
    if ok {
        Ok(id)
    } else {
        Err(format!("invalid game id: {id:?}"))
    }
}

/// Store names come from `window.storeName`, which is `CS-<id>` for a game the
/// app opened and a derived slug for anything else the engine invents.
pub fn validate_store_name(name: &str) -> Result<&str, String> {
    let ok = !name.is_empty()
        && name.len() <= 64
        && name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_' || b == b'.')
        && !name.starts_with('.');
    if ok {
        Ok(name)
    } else {
        Err(format!("invalid store name: {name:?}"))
    }
}

pub fn data_dir(app: &AppHandle) -> Result<PathBuf, String> {
    app.path().app_data_dir().map_err(|e| e.to_string())
}

pub fn games_dir(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(data_dir(app)?.join("games"))
}

pub fn game_dir(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    Ok(games_dir(app)?.join(validate_id(id)?))
}

pub fn manifest_file(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    Ok(game_dir(app, id)?.join("manifest.json"))
}

pub fn scenes_dir(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    Ok(game_dir(app, id)?.join("scenes"))
}

pub fn assets_dir(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    Ok(game_dir(app, id)?.join("assets"))
}

pub fn stores_dir(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(data_dir(app)?.join("stores"))
}

pub fn store_file(app: &AppHandle, name: &str) -> Result<PathBuf, String> {
    Ok(stores_dir(app)?.join(format!("{}.json", validate_store_name(name)?)))
}

/// Presence of this file means the bundled archives have already been offered.
/// A game the player deleted must not reappear on the next launch.
pub fn bundled_marker(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(data_dir(app)?.join("bundled.marker"))
}

pub fn ensure_dirs(app: &AppHandle) -> Result<(), String> {
    for dir in [games_dir(app)?, stores_dir(app)?] {
        std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_ids_that_escape_the_library() {
        assert!(validate_id("..").is_err());
        assert!(validate_id("../etc").is_err());
        assert!(validate_id("a/b").is_err());
        assert!(validate_id("").is_err());
        assert!(validate_id("UPPERCASE").is_err());
        assert!(validate_id("0f3a9c1177ab41de").is_ok());
    }

    #[test]
    fn store_names_allow_the_engine_slug_but_not_traversal() {
        assert!(validate_store_name("CS-0f3a9c1177ab41de").is_ok());
        assert!(validate_store_name("CS-mygame").is_ok());
        assert!(validate_store_name("../../etc/passwd").is_err());
        assert!(validate_store_name(".hidden").is_err());
        assert!(validate_store_name("").is_err());
    }
}
